application: alechewitt-1021
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /dist/(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /static/(.+)
  static_files: static/\1
  upload: static/(.*)

- url: /send_email
  script: main.app

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^\.idea$
- ^node_modules$
